apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ng-ingress
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/canary: "true"
      nginx.ingress.kubernetes.io/canary-weight: "70"
spec:
    rules:
    - host: a810daf8270494cc4a85477ec44b8c41-7a515680a46d7bc7.elb.us-east-1.amazonaws.com
      http:
        paths:
        - backend:
            serviceName: nginx-svc
            servicePort: 80
          path: /
  